# lorealdb/__init__.pyi

from typing import Dict, List, Optional, Tuple

class DBEngineWriteOptimized:
    def __init__(self, path: str) -> None: ...
    def insert_raw(self, id: str, payload: bytes) -> None: ...
    def insert_many_raw(self, records: List[Tuple[str, bytes]]) -> None: ...
    def get(self, id: str) -> Optional[bytes]: ...
    def get_many(self, ids: List[str]) -> Dict[str, Optional[bytes]]: ...
    def delete(self, id: str) -> bool: ...
    def scan_prefix(self, prefix: str) -> Dict[str, bytes]: ...

class DBEngine:
    def __init__(self, path: str) -> None: ...
    def insert(self, id: str, payload: bytes) -> None: ...
    def insert_many(self, records: List[Tuple[str, bytes]]) -> None: ...
    def insert_raw(self, id: str, payload: bytes) -> None: ...
    def insert_many_raw(self, records: List[Tuple[str, bytes]]) -> None: ...
    def get(self, id: str) -> Optional[bytes]: ...
    def get_many(self, ids: List[str]) -> Dict[str, Optional[bytes]]: ...
    def delete(self, id: str) -> bool: ...
    def scan_prefix(self, prefix: str) -> Dict[str, bytes]: ...
    def filter_by_metadata(
        self, index_key: str, index_value: str
    ) -> Dict[str, bytes]: ...
