# lorealdb/__init__.pyi

from typing import Any

class DBEngineWriteOptimized:
    def __init__(self, path: str) -> None: ...
    def insert_raw(self, id: str, payload: bytes) -> None: ...
    def insert_many_raw(self, records: list[tuple[str, bytes]]) -> None: ...
    def get(self, id: str) -> bytes | None: ...
    def get_many(self, ids: list[str]) -> dict[str, bytes | None]: ...
    def delete(self, id: str) -> bool: ...
    def scan_prefix(self, prefix: str) -> dict[str, bytes]: ...

class DBEngine:
    def __init__(self, path: str) -> None: ...
    def insert(self, id: str, payload: dict[str, Any]) -> None: ...
    def insert_many(self, records: list[tuple[str, dict[str, Any]]]) -> None: ...
    def insert_json(self, id: str, json_payload: str) -> None: ...
    def insert_many_json(self, records: list[tuple[str, str]]) -> None: ...
    def upsert(self, id: str, payload: dict[str, Any]) -> None: ...
    def get(self, id: str) -> dict[str, Any] | None: ...
    def get_many(self, ids: list[str]) -> list[tuple[str, dict[str, Any] | None]]: ...
    def delete(self, id: str) -> None: ...
    def scan_prefix(self, prefix: str) -> list[tuple[str, dict[str, Any]]]: ...
    def filter_by_metadata(
        self, index_key: str, index_value: str
    ) -> list[tuple[str, dict[str, Any]]]: ...
    def close_engine(self) -> None: ...
